services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 10

  cache:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10
    depends_on:
      - db

  service1:
    image: busybox
    command: ["sh", "-c", "sleep 30"]
    depends_on:
      - cache

  service2:
    image: busybox
    command: ["sh", "-c", "sleep 30"]
    depends_on:
      - service1

  service3:
    image: busybox
    command: ["sh", "-c", "sleep 30"]
    depends_on:
      - service2

  service4:
    image: busybox
    command: ["sh", "-c", "sleep 30"]
    depends_on:
      - service3

  service5:
    image: busybox
    command: ["sh", "-c", "sleep 30"]
    depends_on:
      - service4

  service6:
    image: busybox
    command: ["sh", "-c", "sleep 30"]
    depends_on:
      - service5
