version: "3.8"

x-security: &security
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped

x-watchtower: &watchtower
  labels:
    - com.centurylinklabs.watchtower.enable=true


services:

# =========================================================
# POSTGRES (internal only)
# =========================================================
  matrix-postgres:
    image: postgres:15-alpine
    container_name: matrix-postgres

    environment:
      POSTGRES_USER: synapse
      POSTGRES_PASSWORD: matrixpass
      POSTGRES_DB: synapse
      POSTGRES_INITDB_ARGS: "--locale=C --encoding=UTF8"

    volumes:
      - /mnt/nvme/docker/matrix/postgres:/var/lib/postgresql/data

    networks:
      - ichor

    <<: *security


# =========================================================
# SYNAPSE (direct port via Tailscale)
# =========================================================
  matrix-synapse:
    image: matrixdotorg/synapse:latest
    container_name: matrix-synapse

    depends_on:
      - matrix-postgres

    volumes:
      - /mnt/nvme/docker/matrix/synapse:/data

    ports:
      - "8008:8008"   # Matrix API

    networks:
      - ichor

    <<: [*security, *watchtower]


# =========================================================
# ELEMENT WEB (direct port via Tailscale)
# =========================================================
  element:
    image: vectorim/element-web:latest
    container_name: element

    volumes:
      - /mnt/nvme/docker/matrix/element/config.json:/app/config.json

    ports:
      - "3040:80"   # Element runs on 8080 internally

    networks:
      - ichor

    <<: [*security, *watchtower]



# =========================================================
# NETWORKS
# =========================================================
networks:
  ichor:
    external: true
