version: "3.8"

services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    networks:
      - traefik_traefik
    volumes:
      - /mnt/nas/data/media/music:/music
      - /mnt/nvme/docker/navidrome:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - ND_SCANONSTART=true       # Scan library when container starts
      - ND_SCANFREQ=3600          # Scan every hour (3600 seconds)
    labels:
      - traefik.enable=true
      # HTTPS router
      - traefik.http.routers.navidrome.rule=Host(`hifi.mortalsrv.uk`)
      - traefik.http.routers.navidrome.entrypoints=websecure
      - traefik.http.routers.navidrome.tls=true
      - traefik.http.routers.navidrome.tls.certresolver=letsencrypt
      - traefik.http.services.navidrome.loadbalancer.server.port=4533
      # HTTP router redirects to HTTPS
      - traefik.http.routers.navidrome-http.rule=Host(`hifi.mortalsrv.uk`)
      - traefik.http.routers.navidrome-http.entrypoints=web
      - traefik.http.routers.navidrome-http.middlewares=redirect-to-https
      # Middleware for redirect scheme
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  traefik_traefik:
    external: true
